version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: vuxi_dev
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data