AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 60
    Environment:
      Variables:
        CLUSTER_NAME: website-analyzer-cluster
        SUBNET_ID: subnet-075ca3338ffe81720
        SECURITY_GROUP_ID: sg-08141489273f739f9

Resources:
  # API Gateway
  WebsiteAnalyzerApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'POST, GET, OPTIONS'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"

  # Lambda Functions
  UrlDiscoveryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/url-discovery/
      Handler: index.handler
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - ecs:RunTask
                - ecs:DescribeTasks
                - ecs:ListTasks
              Resource: "*"
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource:
                - "arn:aws:iam::907929922976:role/ecsTaskRole"
                - "arn:aws:iam::907929922976:role/ecsTaskExecutionRole"
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:ListBucket
              Resource:
                - "arn:aws:s3:::website-analyzer-data"
                - "arn:aws:s3:::website-analyzer-data/*"
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteAnalyzerApi
            Path: /url-discovery
            Method: post

  ScreenshotsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/screenshots/
      Handler: index.handler
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - ecs:RunTask
                - ecs:DescribeTasks
                - ecs:ListTasks
              Resource: "*"
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource:
                - "arn:aws:iam::907929922976:role/ecsTaskRole"
                - "arn:aws:iam::907929922976:role/ecsTaskExecutionRole"
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteAnalyzerApi
            Path: /screenshots
            Method: post

  LighthouseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/lighthouse/
      Handler: index.handler
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - ecs:RunTask
                - ecs:DescribeTasks
                - ecs:ListTasks
              Resource: "*"
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource:
                - "arn:aws:iam::907929922976:role/ecsTaskRole"
                - "arn:aws:iam::907929922976:role/ecsTaskExecutionRole"
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteAnalyzerApi
            Path: /lighthouse
            Method: post

  LlmAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/llm-analysis/
      Handler: index.handler
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - ecs:RunTask
                - ecs:DescribeTasks
                - ecs:ListTasks
              Resource: "*"
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource:
                - "arn:aws:iam::907929922976:role/ecsTaskRole"
                - "arn:aws:iam::907929922976:role/ecsTaskExecutionRole"
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteAnalyzerApi
            Path: /llm-analysis
            Method: post

  FormattingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/formatting/
      Handler: index.handler
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - ecs:RunTask
                - ecs:DescribeTasks
                - ecs:ListTasks
              Resource: "*"
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource:
                - "arn:aws:iam::907929922976:role/ecsTaskRole"
                - "arn:aws:iam::907929922976:role/ecsTaskExecutionRole"
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteAnalyzerApi
            Path: /formatting
            Method: post

  HtmlReportsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/html-reports/
      Handler: index.handler
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - ecs:RunTask
                - ecs:DescribeTasks
                - ecs:ListTasks
              Resource: "*"
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource:
                - "arn:aws:iam::907929922976:role/ecsTaskRole"
                - "arn:aws:iam::907929922976:role/ecsTaskExecutionRole"
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteAnalyzerApi
            Path: /html-reports
            Method: post

  JobStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/job-status/
      Handler: index.handler
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - ecs:RunTask
                - ecs:DescribeTasks
                - ecs:ListTasks
              Resource: "*"
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource:
                - "arn:aws:iam::907929922976:role/ecsTaskRole"
                - "arn:aws:iam::907929922976:role/ecsTaskExecutionRole"
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:ListBucket
              Resource:
                - "arn:aws:s3:::website-analyzer-data"
                - "arn:aws:s3:::website-analyzer-data/*"
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteAnalyzerApi
            Path: /job/{jobId}/status
            Method: get

Outputs:
  ApiUrl:
    Description: 'API Gateway endpoint URL'
    Value: !Sub 'https://${WebsiteAnalyzerApi}.execute-api.${AWS::Region}.amazonaws.com/prod'